### ISSUE TITLE
Receive "Error displaying widget"

### ISSUE THREAD

**Issue by daniel-fink** [opengeos/mapwidget#13]
### Environment Information

-   mapwidget version: "^0.1.2"
-   Python version: 3.10.12
-   Operating System: macOS Version 13.5 (22G74) (on M1), Firefox 116.0.3 (64-bit)

### Description

On repeating basic Leaflet map example (https://mapwidget.gishub.org/examples/leaflet/)
I receive a 'Error displaying widget' after attempting to display map

### What I Did

On inspection of the Web Console, errors are populated regarding `Error: Could not create a view for model id`, or `TypeError: class constructors must be invoked with 'new'`
See screenshot:

<img width="1719" alt="image" src="https://github.com/opengeos/mapwidget/assets/32397975/b73eb76e-652d-482e-8219-f9cf31b5523a">

**Comment by giswqs** [comment]
Thank you for reporting. Did you install it using pip or conda?

**Comment by daniel-fink** [comment]
I installed via poetry

**Comment by giswqs** [comment]
If possible, try installing it using conda. Sometimes pip or poetry might have difficulty in getting the js libraries right. 
https://mapwidget.gishub.org/installation/#install-from-conda-forge

This is a very common issue with ipylealfet. See https://github.com/jupyter-widgets/ipyleaflet/issues?q=error+displaying+widgets

**Comment by daniel-fink** [comment]
Thanks. There must be something amiss with my poetry env. 
For reference, on creating a fresh poetry env, with only jupyter and madwidget dependencies, all worked.

**Comment by giswqs** [comment]
Great to hear that you sorted things out.
