### ISSUE TITLE
Add PMTiles support to MapLibre

### ISSUE THREAD

**Issue by daniel-fink** [opengeos/mapwidget#14]
Is there a way to support adding PMTiles to MapWidget MapLibre maps?

PMTiles are an open-source solution for single-file archive format for tiled data:
> A PMTiles archive can be hosted on a commodity storage platform such as S3, and enables low-cost, zero-maintenance map applications that are "serverless" - free of a custom tile backend or third party provider.

See [https://github.com/protomaps/PMTiles](https://github.com/protomaps/PMTiles) and [https://protomaps.com/docs/pmtiles](https://protomaps.com/docs/pmtiles
)

For use in MapLibre, it apparently needs an additional JS plugin (see [https://protomaps.com/docs/frontends/maplibre](https://protomaps.com/docs/frontends/maplibre) -- "For reading PMTiles directly from cloud storage, you'll need the pmtiles JavaScript library."

**Comment by giswqs** [comment]
I am aware of PMTiles. I tried to use it before. See the relevant issues below. I am not a JavaScript user, and I am not capable of making it work at the moment. Contrbutions are welcome.

https://github.com/protomaps/PMTiles/discussions/209
https://github.com/widgetti/ipyreact/issues/44

**Comment by daniel-fink** [comment]
Thanks for the response. I am also not proficient at JS. Forgive my naivety, but this example looks like it simply enables pmtiles to be added to a maplibre map via loading a JS library in an HTML page: 
https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html#L7C36-L7C36, and the content is specified in line 24 of the <script> tag: `let PMTILES_URL = "https://protomaps.github.io/PMTiles/protomaps(vector)ODbL_firenze.pmtiles";`

Is there a way to also enable loading the pmtiles JS Library within the MapLibre MapWidget? I am OK with the content needing to be loaded from a (local or remote) webserver. The idea is I could specify this content in a string used in the `.set_esm()` method

**Comment by giswqs** [comment]
You can try modifying the js code in this file to see if it works. 
https://github.com/opengeos/mapwidget/blob/master/mapwidget/javascript/maplibre.js

**Comment by daniel-fink** [comment]
For future readers: I couldn't manage to accomplish this via mapwidget. I did succeed however in simply iframe-ing a local .html with `<script src=...>' tags a la the PMTiles example (https://github.com/protomaps/PMTiles/blob/main/js/examples/maplibre.html)

**Comment by giswqs** [comment]
Leafmap now support MapLibre PMTiles. See this example. 
https://leafmap.org/notebooks/93_maplibre_pmtiles/
